### ISSUE TITLE
US7 Als gebruiker wil ik mijn voorkeur taal en afstand in kunnen stellen

### ISSUE THREAD

**Issue by Kev4ever** [TimMaasGeesteranus/AangevuldeRealiteit#51]
- [x] SettingsPage aanmaken
- [x] Radius instelling implementeren
- [x] Radius Cirkel implementeren
- [x] Languages instelling implementeren
- [x] Settings page koppelen aan de rest van de applicatie
- [x] Knop om terug naar het camera view te gaan

**Comment by cyclops1007** [comment]
- [x] SettingsPage aanmaken
- [x] Radius instelling implementeren
- [x] Radius Cirkel implementeren
- [ ] Languages instelling implementeren
- [ ] Settings page koppelen aan de rest van de applicatie
- [ ] Knop om terug naar het camera view te gaan
